// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi58CtG2KSMbipLPHRA3-nkYcBxOz-eks',
    appId: '1:266091057762:web:8de19dad38229b62b2f73b',
    messagingSenderId: '266091057762',
    projectId: 'tp2exam-8521e',
    authDomain: 'tp2exam-8521e.firebaseapp.com',
    storageBucket: 'tp2exam-8521e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDY73rGeg7E2lBeuPPAeOag96YvN8-UIw',
    appId: '1:266091057762:android:d99365e7a5bf4b45b2f73b',
    messagingSenderId: '266091057762',
    projectId: 'tp2exam-8521e',
    storageBucket: 'tp2exam-8521e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE4a3tamga_sfoA4EJ6dlTxdLgRyxgf9U',
    appId: '1:266091057762:ios:8519321398fc2b57b2f73b',
    messagingSenderId: '266091057762',
    projectId: 'tp2exam-8521e',
    storageBucket: 'tp2exam-8521e.firebasestorage.app',
    iosBundleId: 'com.example.tp2exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE4a3tamga_sfoA4EJ6dlTxdLgRyxgf9U',
    appId: '1:266091057762:ios:8519321398fc2b57b2f73b',
    messagingSenderId: '266091057762',
    projectId: 'tp2exam-8521e',
    storageBucket: 'tp2exam-8521e.firebasestorage.app',
    iosBundleId: 'com.example.tp2exam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi58CtG2KSMbipLPHRA3-nkYcBxOz-eks',
    appId: '1:266091057762:web:c402123d12431689b2f73b',
    messagingSenderId: '266091057762',
    projectId: 'tp2exam-8521e',
    authDomain: 'tp2exam-8521e.firebaseapp.com',
    storageBucket: 'tp2exam-8521e.firebasestorage.app',
  );
}
